"""add unique constraint flow email on commitment

Revision ID: 18b4b85760f8
Revises: bfa6b8bc9159
Create Date: 2026-04-22 11:01:28.210411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b4b85760f8'
down_revision: Union[str, Sequence[str], None] = 'bfa6b8bc9159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_commitment_flow_email', 'commitment', ['flow_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_commitment_flow_email', 'commitment', type_='unique')
    # ### end Alembic commands ###
