"""initial reset

Revision ID: 37138291b953
Revises: 
Create Date: 2026-04-24 09:41:22.784607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37138291b953'
down_revision: Union[str, Sequence[str], None] = '3909109c2167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'method' not in existing_tables:
        op.create_table('method',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('price', sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column('description', sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if 'session' not in existing_tables:
        op.create_table('session',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('method_id', sa.UUID(), nullable=True),
        sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('capacity', sa.Integer(), nullable=False),
        sa.Column('instructor', sa.String(length=200), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint('end_time > start_time', name='ck_session_end_after_start'),
        sa.ForeignKeyConstraint(['method_id'], ['method.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_session_start_time', 'session', ['start_time'], unique=False)

    if 'booking' not in existing_tables:
        op.create_table('booking',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('session_id', sa.UUID(), nullable=True),
        sa.Column('first_name', sa.String(length=255), nullable=False),
        sa.Column('last_name', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('notes', sa.String(length=1000), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('session_id', 'email', name='uq_booking_session_email')
        )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_index('ix_session_start_time', table_name='session')
    op.drop_table('session')
    op.drop_table('method')
    # ### end Alembic commands ###
