"""converted back to using datetime(timezone=True) to keep things simple

Revision ID: 4e9ca87f7300
Revises: 9e7ef333ed58
Create Date: 2026-04-23 13:08:31.453924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9ca87f7300'
down_revision: Union[str, Sequence[str], None] = '9e7ef333ed58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
