"""add indexes on flow start_time and commitment flow_id

Revision ID: 61c18b5ddece
Revises: 18b4b85760f8
Create Date: 2026-04-22 11:13:06.624060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c18b5ddece'
down_revision: Union[str, Sequence[str], None] = '18b4b85760f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_commitment_flow_id', 'commitment', ['flow_id'], unique=False)
    op.create_index('ix_flow_start_time', 'flow', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flow_start_time', table_name='flow')
    op.drop_index('ix_commitment_flow_id', table_name='commitment')
    # ### end Alembic commands ###
