"""Regenerate models with new constraints

Revision ID: 7e0ccd54ee91
Revises: cf310ec35bb6
Create Date: 2026-04-22 10:40:02.703339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e0ccd54ee91'
down_revision: Union[str, Sequence[str], None] = 'cf310ec35bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('commitment_flow_id_fkey'), 'commitment', type_='foreignkey')
    op.create_foreign_key(None, 'commitment', 'flow', ['flow_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commitment', type_='foreignkey')
    op.create_foreign_key(op.f('commitment_flow_id_fkey'), 'commitment', 'flow', ['flow_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
