"""add idempotency key to bookings

Revision ID: 8cf7acfc4918
Revises: 2c8126ca1bc9
Create Date: 2026-04-21 13:40:04.270881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cf7acfc4918'
down_revision: Union[str, Sequence[str], None] = '2c8126ca1bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notion_page_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('capacity >= 1', name='resources_capacity_positive'),
    sa.CheckConstraint('duration_minutes > 0', name='resources_duration_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_notion_page_id'), 'resources', ['notion_page_id'], unique=False)
    op.create_table('availability_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='rules_valid_dow'),
    sa.CheckConstraint('end_time > start_time', name='rules_end_after_start'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rules_resource_dow', 'availability_rules', ['resource_id', 'day_of_week'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('customer_email', sa.String(length=320), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('time_range', postgresql.TSTZRANGE(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    postgresql.ExcludeConstraint((sa.column('resource_id'), '='), (sa.column('time_range'), '&&'), where=sa.text("status IN ('pending', 'confirmed')"), using='gist', name='bookings_no_overlap'),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'cancelled', 'completed')", name='bookings_valid_status'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_index('ix_rules_resource_dow', table_name='availability_rules')
    op.drop_table('availability_rules')
    op.drop_index(op.f('ix_resources_notion_page_id'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
