"""removed equal date constraint for flow

Revision ID: b25b981cc4c9
Revises: 4e9ca87f7300
Create Date: 2026-04-23 13:18:16.199859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25b981cc4c9'
down_revision: Union[str, Sequence[str], None] = '4e9ca87f7300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
