"""created user model and updated booking to rely on user

Revision ID: c21ff304396c
Revises: 37138291b953
Create Date: 2026-04-25 13:49:12.475628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c21ff304396c'
down_revision: Union[str, Sequence[str], None] = '37138291b953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_constraint('session_method_id_fkey', 'session', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('method')
    op.drop_table('booking')
    op.drop_index(op.f('ix_session_start_time'), table_name='session')
    op.drop_table('session')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('method_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('instructor', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_session_end_after_start')),
    sa.ForeignKeyConstraint(['method_id'], ['method.id'], name=op.f('session_method_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('session_pkey'))
    )
    op.create_index(op.f('ix_session_start_time'), 'session', ['start_time'], unique=False)
    op.create_table('booking',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('booking_session_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('booking_pkey')),
    sa.UniqueConstraint('session_id', 'email', name=op.f('uq_booking_session_email'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('method',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('method_pkey'))
    )
    # ### end Alembic commands ###
